
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "PAL SEP TEXTO TIPOregbibtex : referenciasreferencias : referencias referenciareferencias : referencia : TIPOreg '{' chaveCitacao ',' campos '}'chaveCitacao : PALcampos : campos ',' campocampos : campocampo : nomeCampo SEP valorCamponomeCampo : PALvalorCampo : TEXTO"
    
_lr_action_items = {'TIPOreg':([0,2,3,14,],[-3,4,-2,-4,]),'$end':([0,1,2,3,14,],[-3,0,-1,-2,-4,]),'{':([4,],[5,]),'PAL':([5,8,13,],[7,12,12,]),',':([6,7,9,10,16,17,18,],[8,-5,13,-7,-6,-8,-10,]),'}':([9,10,16,17,18,],[14,-7,-6,-8,-10,]),'SEP':([11,12,],[15,-9,]),'TEXTO':([15,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'bibtex':([0,],[1,]),'referencias':([0,],[2,]),'referencia':([2,],[3,]),'chaveCitacao':([5,],[6,]),'campos':([8,],[9,]),'campo':([8,13,],[10,16,]),'nomeCampo':([8,13,],[11,11,]),'valorCampo':([15,],[17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> bibtex","S'",1,None,None,None),
  ('bibtex -> referencias','bibtex',1,'p_bibtex','main.py',7),
  ('referencias -> referencias referencia','referencias',2,'p_referencias_lista','main.py',11),
  ('referencias -> <empty>','referencias',0,'p_referencias_vazia','main.py',16),
  ('referencia -> TIPOreg { chaveCitacao , campos }','referencia',6,'p_referencia','main.py',20),
  ('chaveCitacao -> PAL','chaveCitacao',1,'p_chaveCitacao','main.py',24),
  ('campos -> campos , campo','campos',3,'p_campos_lista','main.py',29),
  ('campos -> campo','campos',1,'p_campos_vazia','main.py',33),
  ('campo -> nomeCampo SEP valorCampo','campo',3,'p_campo','main.py',37),
  ('nomeCampo -> PAL','nomeCampo',1,'p_nomeCampo','main.py',41),
  ('valorCampo -> TEXTO','valorCampo',1,'p_valorCampo','main.py',45),
]
